// flow-typed signature: 5706f703c184478873e4f459204dfe36
// flow-typed version: <<STUB>>/@types/graphql_v^14.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/graphql' {
  declare module.exports: any;
}
