// flow-typed signature: 6c993e223bac0cb637c2eb3a40b275a0
// flow-typed version: <<STUB>>/graphql-type-json_v^0.3.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-type-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-type-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-type-json/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-type-json/lib/index.js' {
  declare module.exports: $Exports<'graphql-type-json/lib/index'>;
}
