// flow-typed signature: 541590ed61d2177100c829aac106c72f
// flow-typed version: <<STUB>>/tslint-plugin-prettier_v^2.0.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-plugin-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-plugin-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tslint-plugin-prettier/rules/index' {
  declare module.exports: any;
}

declare module 'tslint-plugin-prettier/rules/prettierRule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tslint-plugin-prettier/rules/index.js' {
  declare module.exports: $Exports<'tslint-plugin-prettier/rules/index'>;
}
declare module 'tslint-plugin-prettier/rules/prettierRule.js' {
  declare module.exports: $Exports<'tslint-plugin-prettier/rules/prettierRule'>;
}
