// flow-typed signature: 91876c3318027e67af0655717fb5169f
// flow-typed version: <<STUB>>/tslint-config-prettier_v^1.18.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-config-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tslint-config-prettier/bin/check' {
  declare module.exports: any;
}

declare module 'tslint-config-prettier/lib/checker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tslint-config-prettier/bin/check.js' {
  declare module.exports: $Exports<'tslint-config-prettier/bin/check'>;
}
declare module 'tslint-config-prettier/lib/checker.js' {
  declare module.exports: $Exports<'tslint-config-prettier/lib/checker'>;
}
