# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: yarn
      - name: Test & lint
        run: yarn test
        env:
          CI: true
      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: JUnit Annotations for Node ${{ matrix.node-version }}
          report_paths: '**/coverage/junit/**/*.xml'
      - name: Testing with previous graphql versions
        run: yarn test-prev-vers
        env:
          CI: true      
      - name: Send codecov.io stats
        if: matrix.node-version == '12.x'
        run: bash <(curl -s https://codecov.io/bash) || echo ''

  publish:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node_modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Semantic Release (publish to npm)
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

